[package]
autobins = false
autoexamples = false
name = "rust-exe"
description = "#!/usr/bin/env rust"
edition = "2021"
version = "0.0.0-shebang"

[[bin]]
name = "rust"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.1"
eyre = "0.6.8"
home = "0.5.3"
once_cell = "1.12.0"
proc-macro2 = { version = "1.0.39", features = ["span-locations"] }
quote = "1.0.18"
sha-1 = "0.10.0"
syn = { version = "1.0.96", features = ["full", "extra-traits", "visit", "visit-mut", "fold"] }
toml = "0.5.9"
tracing = "0.1.34"
env_logger = "0.9.0"
fs2 = "0.4.3"

[dev-dependencies]
expect-test = "1.3.0"

[profile.release]
debug = true
lto = "fat"
opt-level = 3
codegen-units = 1
