condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
newline_style = "Unix"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
