name: rust

on:
  push:
    branches:
      - trunk
      - staging
      - trying

  pull_request:
    branches:
      - trunk

  schedule:
    - cron: '44 2 * * 0'

  workflow_dispatch:

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test

  rust-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  ok:
    needs:
      - rust-test
      - rust-clippy
      - rust-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
