name: rust

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "trunk" ]
  schedule:
    - cron: '44 2 * * 0'

jobs:
  rust-clippy-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - run: cargo install clippy-sarif sarif-fmt cargo-format

      - name: Run clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      - run: cargo test

      - run: cargo format --check
